POST http://localhost:5000/pii_demo HTTP/1.1
content-type: application/json

{
    "lines": [
        "특히 둘째 출산 후 몸무게가 63kg까지 치솟았다고 밝혔지만 체중 증가가 무색할 정도로 변함없는 비주얼을 자랑해 감탄을 안겼다.\n", 
        "매니저는 \"선배님께서는 배우 생활 내내 몸무게 53kg를 넘긴 적이 없다\"라고 제보해 이목을 집중시킨다.\n", 
        "과거 루푸스 병으로 인한 스테로이드 부작용으로 몸무게가 96kg까지 증가했지만 무려 44kg 감량에 성공하며 큰 화제를 모으기도 했다.\n"
        ]
}